"""rate table update

Revision ID: 7ac90211e7ae
Revises: 16b0ed453ecd
Create Date: 2025-02-10 04:09:39.814098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ac90211e7ae"
down_revision: Union[str, None] = "16b0ed453ecd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rates")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rates",
        sa.Column("anecdote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["anecdote_id"], ["anecdotes.id"], name="rates_anecdote_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="rates_user_id_fkey"),
        sa.PrimaryKeyConstraint("anecdote_id", "user_id", name="rates_pkey"),
    )
    # ### end Alembic commands ###
