"""remove abstract from rate table

Revision ID: ea6ddceb735e
Revises: 7ac90211e7ae
Create Date: 2025-02-10 04:12:35.529534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea6ddceb735e"
down_revision: Union[str, None] = "7ac90211e7ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
